FROM node:alpine

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json /app
#COPY package-lock.json ./
RUN npm run install

COPY . /app

# RUN yarn install


CMD ["npm", "run", "start"]

